language: cpp
compiler:
  - g++
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    - george-edison55-precise-backports
    packages:
    - gcc-7
    - g++-7
    - clang-7
    - cmake
    - cmake-data
    env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab5-poly
  - make -j
  - cd ./bin/
  - ./test_poly --gtest_list_tests
notifications:
  email: false
