language: cpp
compiler:
  - g++ -fpermissive
  - clang
before_script:
  - mkdir ../build
  - cd ../build
  - sudo apt install clang-7 g++-8
script:
  - cmake ../mp2-lab5-poly
  - make -j
  - cd ./bin/
  - ./test_poly --gtest_list_tests
notifications:
  email: false
