language: cpp
compiler:
  - g++
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    - george-edison55-precise-backports
    packages:
    - gcc
    - g++
    - clang
    - cmake
    - cmake-data
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab5-poly
  - make -j
  - cd ./bin/
  - ./test_poly --gtest_list_tests
notifications:
  email: false
