os: linux
dist: xenial
language: cpp
compiler:
  - g++
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab5-poly
  - make -j
  - cd ./bin/
  - ./test_poly --gtest_list_tests
notifications:
  email: false
